### ISSUE TITLE
ImportError: cannot import name interpolate

### ISSUE THREAD

**Issue by xiaoweihappy123** [zhanghang1989/gluoncv-torch#20]
from torch.nn.functional import interpolate
ImportError: cannot import name interpolate

Does anyone have this problem?Pytorch = 0.4.0 and python = 2.7.13
What causes it?

**Comment by zhanghang1989** [comment]
Please use PyTorch 1.0

**Comment by xiaoweihappy123** [comment]
Thank you very much！

**Comment by MeteoRex11** [comment]
> Please use PyTorch 1.0

Hi. My model is based off of PyTorch 0.4.0, and It leads to incompatibility issues with the linked cudnn  if i use PyTorch 1.0. Is there any way to make this work on PyTorch 0.4.0?
